### ISSUE TITLE
Logging to right person.

### ISSUE THREAD

**Issue by incognitozen** [ringcentral/pipedrive-embeddable-ringcentral-phone-spa#10]
It looks like the calls are logged to the same person despite them not having the phone number.

![callog](https://user-images.githubusercontent.com/32048201/57281496-6f19cd00-70ee-11e9-9673-032f08b58282.png)

**Comment by zxdong262** [comment]
How about the from number, is it in pipedrive contacts?

**Comment by incognitozen** [comment]
Hey @zxdong262

The calls are all to different numbers but they are all logged to the same person.

So I called 3 different people with three different numbers +61433647772 , +61352216044, +61419099968 but they are all logged to this same person instead of being logged in 3 different people. Hope that makes sense.

**Comment by zxdong262** [comment]
@incognitozen I mean the caller number is in contact list, is it? If so, the log would find the match, and sync to this caller as expected.

**Comment by incognitozen** [comment]
@zxdong262 - Yes the called number is in the pipedrive as a contact and linked to another person. However since yesterday all the calls are being logged into one single person regardless of whether they have the phone number or not.

**Comment by zxdong262** [comment]
I will release a new version to support sync to caller and callee. @incognitozen Thank you for the feedback.

**Comment by zxdong262** [comment]
https://github.com/ringcentral/pipedrive-embeddable-ringcentral-phone-spa/releases/tag/v0.4.10
@incognitozen Now support sync to all matched contacts, let me know how it works.

**Comment by zxdong262** [comment]
Close it now, feel free to submit another if needed, feedbacks are always welcome.
