### ISSUE TITLE
Ring Central not showing activities/outbound calls in pipedrive

### ISSUE THREAD

**Issue by iivanradvfn** [ringcentral/pipedrive-embeddable-ringcentral-phone-spa#11]
When I make a call using the Ring Central chrome plugin, the log doesn't appear in activities in pipedrive.

**Comment by zxdong262** [comment]
@iivanradvfn Sorry missed the message, can you check this: https://github.com/ringcentral/hubspot-embeddable-ringcentral-phone/issues/137 to see if it solves your problem.

**Comment by lendhalo** [comment]
I am having this problem trying to see activities/outbound calls or being able to see the note feature next to calls. When I follow the instructions from the link above, I do not see Pipedrive to authorize. I only see Google.

**Comment by iivanradvfn** [comment]
Sorry, It didn't work, I did many tests with ringcentral support and still the same, Now I moved for another platform
