### ISSUE TITLE
ringcentral and pipedrive - call time not properly synced

### ISSUE THREAD

**Issue by better125** [ringcentral/pipedrive-embeddable-ringcentral-phone-spa#12]
Hi. 
When making a call, the time that is registered in pipedrive is minus 4 hrs.

Time in my computer setting is correct (mac) and time in pipedrive is correct. Time in my ringcentral phone system is also correct.

For more details of the case, please see  case 09017934 managed by Theresa Binalla

Thanks.

**Comment by zxdong262** [comment]
https://github.com/ringcentral/pipedrive-embeddable-ringcentral-phone-spa/releases/tag/v0.5.4 Please try the latest release, should fix now, thank you for the feedback.

**Comment by better125** [comment]
Yes. It works now.

Thank you!


Edward A. Rodriguez
Conferencista * Coach *  Autor
http://www.EdwardRodriguez.com
