### ISSUE TITLE
RingCentral popup not showing in Pipedrive

### ISSUE THREAD

**Issue by CB1212** [ringcentral/pipedrive-embeddable-ringcentral-phone-spa#13]
We have followed the instructions of uploading the zip file in Chrome as an extension, however when we go to our Pipedrive (as per the last step in the instructions), it doesn't pop up with the RingCentral window as expected. 

In the RingCentral Google Chrome extension error log, it gives the error:
Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.
Context
_generated_background_page.html
Stack Trace
_generated_background_page.html:0 (anonymous function)

I messaged RingCentral support, however they directed me to here, so hoping you will be able to help!

Thanks in advance.

**Comment by zxdong262** [comment]
Did you load dist folder as unpacked package? @CB1212

**Comment by CB1212** [comment]
Yes, we clicked on 'Load Unpacked' in developer mode in the Extensions tab in Chrome. That is correct, right?

**Comment by zxdong262** [comment]
Can you see this in your pipedrive.com?
<img width="1438" alt="Screen Shot 2019-07-17 at 1 40 42 PM" src="https://user-images.githubusercontent.com/1641949/61350061-dabfa980-a898-11e9-9915-f30cee2eb2c7.png">

**Comment by CB1212** [comment]
Hi @zxdong262 , 

Thanks for your help. Unfortunately the icon you mentioned isn't showing:
![image](https://user-images.githubusercontent.com/52982594/61414507-7a307b00-a931-11e9-9f00-59752cfca4bc.png)

**Comment by zxdong262** [comment]
Can you try the latest release? If still not working, we can set up a meeting to see what is problem, just tell me your timezone and available time, I will set the meeting.

**Comment by CB1212** [comment]
Hi @zxdong262 , I believe we're already using the latest release, which is what's in the image below:
![image](https://user-images.githubusercontent.com/52982594/61421411-57f72700-a94a-11e9-84b3-77733c9cbdca.png)

Are you available at 7am AEST (Melbourne, Australia time) on Friday 19 July? It would be ideal if you could join us on that call to assist, as we already have a call booked to discuss this.
