### ISSUE TITLE
PipeDrive Contacts not pulling into RingCentral extension

### ISSUE THREAD

**Issue by msmithlp560** [ringcentral/pipedrive-embeddable-ringcentral-phone-spa#15]
Hey All! 

The RingCentral popup is displaying but the PipeDrive contacts are not populating. When I send an SMS, there is a small popout bar that appears on the left hand side that says "contact not found." This is preventing the SMS from populating into the contact. 

![image](https://user-images.githubusercontent.com/53407129/62010981-24c14e80-b127-11e9-98e5-fe74c1362b66.png)

**Comment by msmithlp560** [comment]
![Ring Central](https://user-images.githubusercontent.com/53407129/62011271-f80f3600-b12a-11e9-85da-f3c12cb2eb27.jpg)

**Comment by zxdong262** [comment]
Can you check the browser console, post the screenshot or log here if possible, and how many contacts do you have?

 before it sync all contacts, call/sms log sync will not work, you can check this for more detail.

https://github.com/ringcentral/hubspot-embeddable-ringcentral-phone/issues/137

**Comment by msmithlp560** [comment]
I have probably close to 10k contacts in there. I created a new contact manually and it now populated for me, but only that contact is showing under the pipedrive section of the RC popout.

**Console Log**
import RingCentral Embeddable Voice to web page
app.js:1 u.addSelector is deprecated. Please stop use it soon before the feature is completely removed
(anonymous) @ app.js:1
app.js:1 u requires u._actionTypes to be implemented.
(anonymous) @ app.js:1
app.js:1 u requires l._actionTypes to be implemented.
(anonymous) @ app.js:1
app.js:1 u requires d._actionTypes to be implemented.
(anonymous) @ app.js:1
app.js:1 u requires t._actionTypes to be implemented.
(anonymous) @ app.js:1
app.js:1 u requires u._onStateChange to be implemented.
(anonymous) @ app.js:1
content.js:1 Pipedrive serviceName
content.js:1 Object
content.js:1 Object
adapter.js?prefix=Pipedrive-rc&newAdapterUI=1&userAgent=Pipedrive_extension%2F0.6.1&disableActiveCallControl=false&appKey=faiv8pjETk6cuAGPB3EuGw&appSecret=9ImQ2fH0QvCuflZRgyhNBw_HOlOzzLQZ-BIh2af-ozAQ&appServer=https%3A%2F%2Fplatform.ringcentral.com:5371 rc-login-status-notify: true
content.js:1 Object
content.js:1 rc logined true
content.js:1 Object
adapter.js?prefix=Pipedrive-rc&newAdapterUI=1&userAgent=Pipedrive_extension%2F0.6.1&disableActiveCallControl=false&appKey=faiv8pjETk6cuAGPB3EuGw&appSecret=9ImQ2fH0QvCuflZRgyhNBw_HOlOzzLQZ-BIh2af-ozAQ&appServer=https%3A%2F%2Fplatform.ringcentral.com:5375 rc-calling-settings-notify: Object
content.js:1 Object
content.js:1 Object
adapter.js?prefix=Pipedrive-rc&newAdapterUI=1&userAgent=Pipedrive_extension%2F0.6.1&disableActiveCallControl=false&appKey=faiv8pjETk6cuAGPB3EuGw&appSecret=9ImQ2fH0QvCuflZRgyhNBw_HOlOzzLQZ-BIh2af-ozAQ&appServer=https%3A%2F%2Fplatform.ringcentral.com:5397 rc-route-changed-notify: /dialer
content.js:1 Object
content.js:1 new-wistia-iframe
content.js:1 {"method":"_trigger","args":["leaveviewport"]}
content.js:1 Object
content.js:1 Object
content.js:1 logsync body Object
content.js:1 Object
content.js:1 logsync body Object
content.js:1 Object
content.js:1 logsync body Object
adapter.js?prefix=Pipedrive-rc&newAdapterUI=1&userAgent=Pipedrive_extension%2F0.6.1&disableActiveCallControl=false&appKey=faiv8pjETk6cuAGPB3EuGw&appSecret=9ImQ2fH0QvCuflZRgyhNBw_HOlOzzLQZ-BIh2af-ozAQ&appServer=https%3A%2F%2Fplatform.ringcentral.com:5391 rc-message-updated-notify: 1099471565039
content.js:1 Object
adapter.js?prefix=Pipedrive-rc&newAdapterUI=1&userAgent=Pipedrive_extension%2F0.6.1&disableActiveCallControl=false&appKey=faiv8pjETk6cuAGPB3EuGw&appSecret=9ImQ2fH0QvCuflZRgyhNBw_HOlOzzLQZ-BIh2af-ozAQ&appServer=https%3A%2F%2Fplatform.ringcentral.com:5391 rc-message-updated-notify: 1099475038039
content.js:1 Object
content.js:1 Object
content.js:1 logsync body Object
content.js:1 Object
content.js:1 logsync body Object
content.js:1 Object
content.js:1 logsync body Object
content.js:1 Object
content.js:1 logsync body Object
content.js:1 Object
content.js:1 logsync body Object
content.js:1 Object
content.js:1 logsync body Object
content.js:1 Object
content.js:1 logsync body Object
content.js:1 Object
content.js:1 logsync body Object
content.js:1 Object
content.js:1 logsync body Object
content.js:1 Object
content.js:1 logsync body Object
content.js:1 Object
content.js:1 logsync body Object
content.js:1 Object
content.js:1 logsync body Object
content.js:1 Object
content.js:1 logsync body Object
content.js:1 Object
content.js:1 logsync body Object
content.js:1 Object
content.js:1 logsync body Object
content.js:1 Object
content.js:1 logsync body Object
content.js:1 Object
content.js:1 logsync body Object
content.js:1 Object
content.js:1 logsync body Object
content.js:1 Object
content.js:1 logsync body Object
content.js:1 Object
content.js:1 logsync body Object
content.js:1 Object
content.js:1 logsync body Object
content.js:1 Object
content.js:1 logsync body Object
content.js:1 Object
content.js:1 logsync body Object
content.js:1 Object
content.js:1 logsync body Object
content.js:1 Object
content.js:1 logsync body Object
content.js:1 Object
content.js:1 logsync body Object
content.js:1 Object
content.js:1 logsync body Object
content.js:1 Object
content.js:1 logsync body Object
content.js:1 Object
content.js:1 logsync body Object
content.js:1 Object
content.js:1 logsync body Object
content.js:1 Object
content.js:1 logsync body Object
content.js:1 Object
content.js:1 logsync body Object
content.js:1 Object
content.js:1 logsync body Object
content.js:1 Object
content.js:1 logsync body Object
content.js:1 Object
content.js:1 logsync body Object
content.js:1 Object
content.js:1 logsync body Object
content.js:1 Object
content.js:1 logsync body Object
content.js:1 Object
content.js:1 logsync body Object
content.js:1 Object
content.js:1 logsync body Object
content.js:1 Object
content.js:1 logsync body Object
content.js:1 Object
content.js:1 logsync body Object
content.js:1 Object
content.js:1 logsync body Object
content.js:1 Object
content.js:1 logsync body Object
content.js:1 Object
content.js:1 logsync body Object
content.js:1 Object
content.js:1 logsync body Object
content.js:1 Object
content.js:1 logsync body Object
content.js:1 Object
content.js:1 logsync body Object
content.js:1 Object
content.js:1 logsync body Object
content.js:1 Object
content.js:1 logsync body Object
content.js:1 Object
content.js:1 logsync body Object
content.js:1 Object
content.js:1 logsync body Object
content.js:1 Object
content.js:1 logsync body Object
content.js:1 Object
content.js:1 logsync body Object
content.js:1 Object
content.js:1 logsync body Object
content.js:1 Object
content.js:1 logsync body Object
content.js:1 Object
content.js:1 logsync body Object
content.js:1 Object
content.js:1 logsync body Object
content.js:1 Object
content.js:1 logsync body Object
content.js:1 Object
content.js:1 logsync body Object
content.js:1 Object
content.js:1 logsync body Object
content.js:1 Object
content.js:1 logsync body Object
content.js:1 Object
content.js:1 logsync body Object
content.js:1 Object
content.js:1 logsync body Object
content.js:1 Object
content.js:1 logsync body Object
content.js:1 Object
content.js:1 logsync body Object
content.js:1 Object
content.js:1 logsync body Object
content.js:1 Object
content.js:1 logsync body Object
content.js:1 Object
content.js:1 logsync body Object
content.js:1 Object
content.js:1 logsync body Object
content.js:1 Object
content.js:1 logsync body Object
content.js:1 Object
content.js:1 logsync body Object
content.js:1 Object
content.js:1 logsync body Object
content.js:1 Object
content.js:1 logsync body Object
content.js:1 Object
content.js:1 logsync body Object
content.js:1 Object
content.js:1 logsync body Object
content.js:1 Object
content.js:1 logsync body Object
content.js:1 Object
content.js:1 logsync body Object
content.js:1 Object
content.js:1 logsync body Object
content.js:1 Object
content.js:1 logsync body Object
chrome-extension://lhfpmghdklidnklmompplpkcmphmnlcj/content.js:1 Object
chrome-extension://lhfpmghdklidnklmompplpkcmphmnlcj/content.js:1 logsync body Object
chrome-extension://lhfpmghdklidnklmompplpkcmphmnlcj/content.js:1 Object
chrome-extension://lhfpmghdklidnklmompplpkcmphmnlcj/content.js:1 logsync body Object
chrome-extension://lhfpmghdklidnklmompplpkcmphmnlcj/content.js:1 Object
chrome-extension://lhfpmghdklidnklmompplpkcmphmnlcj/content.js:1 logsync body Object
chrome-extension://lhfpmghdklidnklmompplpkcmphmnlcj/content.js:1 Object
chrome-extension://lhfpmghdklidnklmompplpkcmphmnlcj/content.js:1 logsync body Object
chrome-extension://lhfpmghdklidnklmompplpkcmphmnlcj/content.js:1 Object
chrome-extension://lhfpmghdklidnklmompplpkcmphmnlcj/content.js:1 logsync body Object
chrome-extension://lhfpmghdklidnklmompplpkcmphmnlcj/content.js:1 Object
chrome-extension://lhfpmghdklidnklmompplpkcmphmnlcj/content.js:1 logsync body Object
chrome-extension://lhfpmghdklidnklmompplpkcmphmnlcj/content.js:1 Object
chrome-extension://lhfpmghdklidnklmompplpkcmphmnlcj/content.js:1 logsync body Object
chrome-extension://lhfpmghdklidnklmompplpkcmphmnlcj/content.js:1 Object
chrome-extension://lhfpmghdklidnklmompplpkcmphmnlcj/content.js:1 logsync body Object
chrome-extension://lhfpmghdklidnklmompplpkcmphmnlcj/content.js:1 Object
chrome-extension://lhfpmghdklidnklmompplpkcmphmnlcj/content.js:1 logsync body Object
chrome-extension://lhfpmghdklidnklmompplpkcmphmnlcj/content.js:1 Object
chrome-extension://lhfpmghdklidnklmompplpkcmphmnlcj/content.js:1 logsync body Object
chrome-extension://lhfpmghdklidnklmompplpkcmphmnlcj/content.js:1 Object
chrome-extension://lhfpmghdklidnklmompplpkcmphmnlcj/content.js:1 logsync body Object
chrome-extension://lhfpmghdklidnklmompplpkcmphmnlcj/content.js:1 Object
chrome-extension://lhfpmghdklidnklmompplpkcmphmnlcj/content.js:1 logsync body Object
chrome-extension://lhfpmghdklidnklmompplpkcmphmnlcj/content.js:1 Object
chrome-extension://lhfpmghdklidnklmompplpkcmphmnlcj/content.js:1 logsync body Object
chrome-extension://lhfpmghdklidnklmompplpkcmphmnlcj/content.js:1 Object
chrome-extension://lhfpmghdklidnklmompplpkcmphmnlcj/content.js:1 logsync body Object
chrome-extension://lhfpmghdklidnklmompplpkcmphmnlcj/content.js:1 Object
chrome-extension://lhfpmghdklidnklmompplpkcmphmnlcj/content.js:1 logsync body Object
chrome-extension://lhfpmghdklidnklmompplpkcmphmnlcj/content.js:1 Object
chrome-extension://lhfpmghdklidnklmompplpkcmphmnlcj/content.js:1 logsync body Object
chrome-extension://lhfpmghdklidnklmompplpkcmphmnlcj/content.js:1 Object
chrome-extension://lhfpmghdklidnklmompplpkcmphmnlcj/content.js:1 logsync body Object
chrome-extension://lhfpmghdklidnklmompplpkcmphmnlcj/content.js:1 {"method":"_trigger","args":["plugininitialized","vulcanV2Video"]}
chrome-extension://lhfpmghdklidnklmompplpkcmphmnlcj/content.js:1 {"method":"_trigger","args":["controlenabled","subtitles"]}
chrome-extension://lhfpmghdklidnklmompplpkcmphmnlcj/content.js:1 {"method":"_trigger","args":["controlenabled","captionsButton"]}
chrome-extension://lhfpmghdklidnklmompplpkcmphmnlcj/content.js:1 {"method":"_trigger","args":["plugininitialized","captions-v1"]}
chrome-extension://lhfpmghdklidnklmompplpkcmphmnlcj/content.js:1 {"method":"_trigger","args":["plugininitialized","captions"]}
chrome-extension://lhfpmghdklidnklmompplpkcmphmnlcj/content.js:1 {"method":"_trigger","args":["plugininitialized","share-v2"]}
chrome-extension://lhfpmghdklidnklmompplpkcmphmnlcj/content.js:1 {"method":"_trigger","args":["controlmounted","backgroundFocus"]}
chrome-extension://lhfpmghdklidnklmompplpkcmphmnlcj/content.js:1 {"method":"_trigger","args":["controlmounted","bigPlayButton"]}
chrome-extension://lhfpmghdklidnklmompplpkcmphmnlcj/content.js:1 {"method":"_trigger","args":["clickforsoundvisibilitychange",false]}
chrome-extension://lhfpmghdklidnklmompplpkcmphmnlcj/content.js:1 {"method":"_trigger","args":["controlmounted","clickForSoundButton"]}
chrome-extension://lhfpmghdklidnklmompplpkcmphmnlcj/content.js:1 {"method":"_trigger","args":["controlmounted","contextMenu"]}
chrome-extension://lhfpmghdklidnklmompplpkcmphmnlcj/content.js:1 {"method":"_trigger","args":["controlmounted","focusOutline"]}
chrome-extension://lhfpmghdklidnklmompplpkcmphmnlcj/content.js:1 {"method":"_trigger","args":["controlmounted","fullscreenButton"]}
chrome-extension://lhfpmghdklidnklmompplpkcmphmnlcj/content.js:1 {"method":"_trigger","args":["controlmounted","loadingHourglass"]}
chrome-extension://lhfpmghdklidnklmompplpkcmphmnlcj/content.js:1 {"method":"_trigger","args":["controlmounted","loadingIndicator"]}
chrome-extension://lhfpmghdklidnklmompplpkcmphmnlcj/content.js:1 {"method":"_trigger","args":["controlmounted","lowerPlaybar"]}
chrome-extension://lhfpmghdklidnklmompplpkcmphmnlcj/content.js:1 {"method":"_trigger","args":["controlmounted","playPauseNotifier"]}
chrome-extension://lhfpmghdklidnklmompplpkcmphmnlcj/content.js:1 {"method":"_trigger","args":["controlmounted","settingsButton"]}
chrome-extension://lhfpmghdklidnklmompplpkcmphmnlcj/content.js:1 {"method":"_trigger","args":["controlmounted","smallPlayButton"]}
chrome-extension://lhfpmghdklidnklmompplpkcmphmnlcj/content.js:1 {"method":"_trigger","args":["controlmounted","statusBar"]}
chrome-extension://lhfpmghdklidnklmompplpkcmphmnlcj/content.js:1 {"method":"_trigger","args":["controlmounted","upperPlaybar"]}
chrome-extension://lhfpmghdklidnklmompplpkcmphmnlcj/content.js:1 {"method":"_trigger","args":["controlmounted","volumeButton"]}
chrome-extension://lhfpmghdklidnklmompplpkcmphmnlcj/content.js:1 {"method":"_trigger","args":["controlmounted","captionsButton"]}
chrome-extension://lhfpmghdklidnklmompplpkcmphmnlcj/content.js:1 {"method":"_trigger","args":["controlmounted","subtitles"]}
chrome-extension://lhfpmghdklidnklmompplpkcmphmnlcj/content.js:1 {"method":"_trigger","args":["controlmounted","transcript"]}
chrome-extension://lhfpmghdklidnklmompplpkcmphmnlcj/content.js:1 {"method":"_trigger","args":["controlmounted","shareButton"]}
chrome-extension://lhfpmghdklidnklmompplpkcmphmnlcj/content.js:1 {"method":"_trigger","args":["controlmounted","thumbnail"]}
chrome-extension://lhfpmghdklidnklmompplpkcmphmnlcj/content.js:1 Object
chrome-extension://lhfpmghdklidnklmompplpkcmphmnlcj/content.js:1 logsync body Object
chrome-extension://lhfpmghdklidnklmompplpkcmphmnlcj/content.js:1 Object
chrome-extension://lhfpmghdklidnklmompplpkcmphmnlcj/content.js:1 logsync body Object
chrome-extension://lhfpmghdklidnklmompplpkcmphmnlcj/content.js:1 Object
content.js:1 logsync body Object
content.js:1 Object
content.js:1 logsync body Object
content.js:1 Object
content.js:1 logsync body Object
content.js:1 Object
content.js:1 logsync body Object
content.js:1 Object
content.js:1 logsync body Object
content.js:1 Object
content.js:1 logsync body Object
content.js:1 {"method":"_trigger","args":["playerlanguagechange",{"code":"en-US","text":"English"}]}
content.js:1 {"method":"updateProperties","args":[{"_playerLanguage":{"code":"en-US","text":"English"}}]}
content.js:1 {"method":"_trigger","args":["transitiondone"]}
content.js:1 {"method":"_trigger","args":["engine-initialized"]}
content.js:1 {"method":"_trigger","args":["statechange","beforeplay",null]}
content.js:1 {"method":"updateProperties","args":[{"_state":"beforeplay"}]}
content.js:1 {"method":"_trigger","args":["qualitychange","auto"]}
content.js:1 {"method":"_trigger","args":["transmit-stats","{\"account_key\":\"wistia-production_332632\",\"session_id\":\"900cf7d_6866bac4-78d9-4025-860b-0c8e1ded64dc-227fc2c15-e67588da179f-e01c\",\"media_id\":\"wistia-production_42649693\",\"event_key\":\"f701df1_fce8beda-39a9-4719-b90b-aa637ec75624-7aa0aaa32-16cdad8c311c-00fb\",\"media_duration\":260.442,\"visitor_version\":0,\"referrer\":\"https://lifechanger.pipedrive.com/deal/1015\",\"event_details\":[{\"key\":\"initialized\",\"value\":\"0.0\",\"timeDelta\":5006,\"lastAccountInstance\":14636,\"lastMediaInstance\":14636}],\"foreign_data\":null,\"seconds_watched\":0}"]}
content.js:1 {"method":"_trigger","args":["qualitychange",360]}
adapter.js?prefix=Pipedrive-rc&newAdapterUI=1&userAgent=Pipedrive_extension%2F0.6.1&disableActiveCallControl=false&appKey=faiv8pjETk6cuAGPB3EuGw&appSecret=9ImQ2fH0QvCuflZRgyhNBw_HOlOzzLQZ-BIh2af-ozAQ&appServer=https%3A%2F%2Fplatform.ringcentral.com:5397 rc-route-changed-notify: /messages
content.js:1 Object
adapter.js?prefix=Pipedrive-rc&newAdapterUI=1&userAgent=Pipedrive_extension%2F0.6.1&disableActiveCallControl=false&appKey=faiv8pjETk6cuAGPB3EuGw&appSecret=9ImQ2fH0QvCuflZRgyhNBw_HOlOzzLQZ-BIh2af-ozAQ&appServer=https%3A%2F%2Fplatform.ringcentral.com:5397 rc-route-changed-notify: /conversations/6682943916857924657
content.js:1 Object
adapter.js?prefix=Pipedrive-rc&newAdapterUI=1&userAgent=Pipedrive_extension%2F0.6.1&disableActiveCallControl=false&appKey=faiv8pjETk6cuAGPB3EuGw&appSecret=9ImQ2fH0QvCuflZRgyhNBw_HOlOzzLQZ-BIh2af-ozAQ&appServer=https%3A%2F%2Fplatform.ringcentral.com:5397 rc-route-changed-notify: /messages
content.js:1 Object
adapter.js?prefix=Pipedrive-rc&newAdapterUI=1&userAgent=Pipedrive_extension%2F0.6.1&disableActiveCallControl=false&appKey=faiv8pjETk6cuAGPB3EuGw&appSecret=9ImQ2fH0QvCuflZRgyhNBw_HOlOzzLQZ-BIh2af-ozAQ&appServer=https%3A%2F%2Fplatform.ringcentral.com:5397 rc-route-changed-notify: /conversations/6682943916857924657
content.js:1 Object
adapter.js?prefix=Pipedrive-rc&newAdapterUI=1&userAgent=Pipedrive_extension%2F0.6.1&disableActiveCallControl=false&appKey=faiv8pjETk6cuAGPB3EuGw&appSecret=9ImQ2fH0QvCuflZRgyhNBw_HOlOzzLQZ-BIh2af-ozAQ&appServer=https%3A%2F%2Fplatform.ringcentral.com:5397 rc-route-changed-notify: /messages
content.js:1 Object
adapter.js?prefix=Pipedrive-rc&newAdapterUI=1&userAgent=Pipedrive_extension%2F0.6.1&disableActiveCallControl=false&appKey=faiv8pjETk6cuAGPB3EuGw&appSecret=9ImQ2fH0QvCuflZRgyhNBw_HOlOzzLQZ-BIh2af-ozAQ&appServer=https%3A%2F%2Fplatform.ringcentral.com:5397 rc-route-changed-notify: /conversations/7387564906352077566
content.js:1 Object
content.js:1 Object
content.js:1 Object
content.js:1 logsync body Object
adapter.js?prefix=Pipedrive-rc&newAdapterUI=1&userAgent=Pipedrive_extension%2F0.6.1&disableActiveCallControl=false&appKey=faiv8pjETk6cuAGPB3EuGw&appSecret=9ImQ2fH0QvCuflZRgyhNBw_HOlOzzLQZ-BIh2af-ozAQ&appServer=https%3A%2F%2Fplatform.ringcentral.com:5391 rc-message-updated-notify: 1099475064039
content.js:1 Object
content.js:1 Object
content.js:1 logsync body Object
content.js:1 Object
content.js:1 logsync body Object
content.js:1 Object
content.js:1 logsync body Object
content.js:1 Object
content.js:1 Object
content.js:1 logsync body Object
content.js:1 Object
content.js:1 Object
content.js:1 logsync body Object
content.js:1 Object
content.js:1 Object
content.js:1 logsync body Object
content.js:1 Object
content.js:1 Object
content.js:1 logsync body Object
content.js:1 Object
content.js:1 Object
content.js:1 logsync body Object
content.js:1 Object
content.js:1 Object
content.js:1 use cache
content.js:1 Object
content.js:1 Object
content.js:1 logsync body Object
content.js:1 Object
content.js:1 logsync body Object
content.js:1 use cache
content.js:1 Object
content.js:1 logsync body Object
content.js:1 Object
content.js:1 use cache
content.js:1 Object
content.js:1 logsync body Object
content.js:1 Object
content.js:1 use cache
content.js:1 Object
content.js:1 logsync body Object
content.js:1 Object
content.js:1 use cache
content.js:1 Object
content.js:1 logsync body Object
content.js:1 Object
content.js:1 use cache
content.js:1 Object
content.js:1 logsync body Object
content.js:1 Object
content.js:1 use cache
content.js:1 Object
content.js:1 logsync body Object
content.js:1 Object
content.js:1 use cache
content.js:1 Object
content.js:1 logsync body Object
content.js:1 Object
content.js:1 use cache
content.js:1 Object
content.js:1 logsync body Object
content.js:1 Object
content.js:1 use cache
adapter.js?prefix=Pipedrive-rc&newAdapterUI=1&userAgent=Pipedrive_extension%2F0.6.1&disableActiveCallControl=false&appKey=faiv8pjETk6cuAGPB3EuGw&appSecret=9ImQ2fH0QvCuflZRgyhNBw_HOlOzzLQZ-BIh2af-ozAQ&appServer=https%3A%2F%2Fplatform.ringcentral.com:5397 rc-route-changed-notify: /messages
content.js:1 Object
content.js:1 Object
content.js:1 use cache
adapter.js?prefix=Pipedrive-rc&newAdapterUI=1&userAgent=Pipedrive_extension%2F0.6.1&disableActiveCallControl=false&appKey=faiv8pjETk6cuAGPB3EuGw&appSecret=9ImQ2fH0QvCuflZRgyhNBw_HOlOzzLQZ-BIh2af-ozAQ&appServer=https%3A%2F%2Fplatform.ringcentral.com:5397 rc-route-changed-notify: /contacts
content.js:1 Object
content.js:1 Object
content.js:1 logsync body Object
content.js:1 Object
content.js:1 use cache
adapter.js?prefix=Pipedrive-rc&newAdapterUI=1&userAgent=Pipedrive_extension%2F0.6.1&disableActiveCallControl=false&appKey=faiv8pjETk6cuAGPB3EuGw&appSecret=9ImQ2fH0QvCuflZRgyhNBw_HOlOzzLQZ-BIh2af-ozAQ&appServer=https%3A%2F%2Fplatform.ringcentral.com:5397 rc-route-changed-notify: /settings
content.js:1
![pipedrive RC](https://user-images.githubusercontent.com/53407129/62015401-180d1c80-b160-11e9-81a0-7c84f38580c8.jpg)

**Comment by zxdong262** [comment]
Since you have 10k contacts, it may take minutes to finish the contacts syncing, can you click the reload contacts button to see if it can load all contacts?

If you still can not see contacts in your rc widgets, then we can have a meeting in your convenient time, to find out why, you can send email to drake.zhao@ringcentral.com with your time zone and meeting time, any time is OK.

@msmithlp560

**Comment by zxdong262** [comment]
<img width="120" alt="Screen Shot 2019-07-29 at 1 42 08 P@msmithlp560 " src="https://user-images.githubusercontent.com/1641949/62024210-b5bb2700-b206-11e9-885c-83289d2e2c37.png">
@msmithlp560 This is the reload button

**Comment by msmithlp560** [comment]
@zxdong262 Sent an email this morning (PST). Looking forward to connecting with you. 

The reload didn't work. It is only syncing contacts into the widget that have since been created from the date of adding the widget extension but not old data.

**Comment by msmithlp560** [comment]
When going into my Extensions in Chrome, I see an Error populating:

Content is too long to post here. 


![RC pipes](https://user-images.githubusercontent.com/53407129/62088318-cd4fdb00-b219-11e9-9aca-a2a6184380aa.jpg)

**Comment by zxdong262** [comment]
@msmithlp560 
Done, let me know if it works for you, thank you for the feedback!
https://github.com/ringcentral/pipedrive-embeddable-ringcentral-phone-spa/releases/tag/v0.7.0

**Comment by msmithlp560** [comment]
@zxdong262 Beautiful! Works like a charm -- thank you so much for your help.

**Comment by zxdong262** [comment]
Close it now, feel free to open another issue.
