### ISSUE TITLE
No Audio 

### ISSUE THREAD

**Issue by SeaFist** [ringcentral/pipedrive-embeddable-ringcentral-phone-spa#16]
![CaptureSamantha1](https://user-images.githubusercontent.com/48298504/62635280-fa169780-b969-11e9-8120-3b984b09ae22.PNG)
![CaptureSamantha2](https://user-images.githubusercontent.com/48298504/62635283-fb47c480-b969-11e9-9feb-5743c752ea70.PNG)

Missing Audio Option for PipeDrive

**Comment by zxdong262** [comment]
Navigating to chrome://settings/content/microphone?search=microphone in Chrome. If you see RingCentral in the "Block" list, you will have to remove it by clicking the trash can icon to the right, then quit and reopen Google Chrome, goto pipedrive to see if it popup microphone notification.

@SeaFist

**Comment by SeaFist** [comment]
Hi @zxdong262 The RingCentral is not listed in the blocked list. There is nothing listed in the block list. It is blank.

**Comment by zxdong262** [comment]
@embbnux Any ideas about this?

**Comment by embbnux** [comment]
Hi, @SeaFist Do you have microphone device in your computer?

**Comment by SeaFist** [comment]
> Hi, @SeaFist Do you have microphone device in your computer?

Yes, there is Mic and it is working. This is on a Windows 10 Home, Version 1803

**Comment by SeaFist** [comment]
Please close this ticket. The customer prompted the setting to Calling > My RingCentral Phone.

Thank you guys.
