### ISSUE TITLE
SMS not going out

### ISSUE THREAD

**Issue by jilmartin** [ringcentral/pipedrive-embeddable-ringcentral-phone-spa#19]
Hello, 
I have no experience with IT but managed to integrate Ring Central into Pipedrive. Everything seems to be working fine besides SMS. The log works but the test text does not actually go through. Thank you for being patience with my ignorance.

**Comment by zxdong262** [comment]
@jilmartin Sorry for the delay, As I tested, it synced to deal as well, only requirement is the deal  must have the contact as person property, can you confirm the deal has proper contact set? If so, it is some problem I do not know, maybe you can check browser console to see if there is any errors, and post the message here or we can have a meeting to find out why(you can send your timezone, available time range to drake.zhao@ringcentral.com, I will arrange the meeting and send the meeting link and calendar info)

**Comment by zxdong262** [comment]
@jilmartin Hi, since I have published new releases, I wonder if they fixed the problem.

**Comment by zxdong262** [comment]
Close it now, feel free to submit another if needed, feedbacks are always welcome.
