### ISSUE TITLE
Extension won't pick up syncronizing new contacts

### ISSUE THREAD

**Issue by FilipinaW** [ringcentral/pipedrive-embeddable-ringcentral-phone-spa#22]
I've added a new contact, when I trigger syncing the message stays in the bottom left corner saying that it's syncing ->  it's there for a long time.  It never picks up new contact I just added.  I tried all the versions back to 7.6 - that is the version that finally synced my new contact to the extension. None of the versions under 8 worked for me.  I tried on my PC and laptop - with the same outcome.

**Comment by zxdong262** [comment]
@FilipinaW Sorry for the problem,  I will fix ASAP

**Comment by zxdong262** [comment]
@FilipinaW Now resync fix, but still click another tab and click contacts tab again to show the updated contacts list. Will fix this in a few days, requires other team member's work.

**Comment by zxdong262** [comment]
@FilipinaW Done

**Comment by FilipinaW** [comment]
@zxdong262 still seem to have an issue.  Running 8.6.

**Comment by zxdong262** [comment]
@FilipinaW Can you share a screenshot of the problem and the browser console errors if possible? Thank you.

**Comment by FilipinaW** [comment]
Hi @zxdong262 .  What is the status on the syncing issue?  We changed all hardware at our office, and I would like to install the extension for everyone - yet I can't seem to find past releases online as well.

**Comment by zxdong262** [comment]
@FilipinaW Can not reproduce.

**Comment by FilipinaW** [comment]
with the last release 1.1.0 contacts get picked up on the contact tab, but do not match to the histoyr log.  I can't log any calls as this point.  See errors:
![image](https://user-images.githubusercontent.com/47257281/68422800-de8c7a00-016e-11ea-9608-911b86dd93be.png)

**Comment by zxdong262** [comment]
@FilipinaW Did you try reload the contacts? By click the reload icon?
<img width="345" alt="Screen Shot 2019-11-08 at 6 52 04 AM" src="https://user-images.githubusercontent.com/1641949/68434618-62d51080-01f4-11ea-8ded-0a88e28f15b7.png">

**Comment by FilipinaW** [comment]
yes, multiple times.  Also.. the contacts that showed in the contact list yesterday that didn't sync to the call history log, are not there this morning.  Does it have to be reloaded every day?  Keep in mind we are on Canadian account, and I know there were some issues related to that in the past.

**Comment by FilipinaW** [comment]
Is there a possible fix coming?  The new extension is not matching any contacts to the log.  Is this a number format issue?  Is it Canadian account issue?  I'd love to have my company use the RC Chrome extension, as that was one of the reasons we purchased Pipedrive... but currently I can't install any of the new releases as they are not working.

**Comment by zxdong262** [comment]
@FilipinaW Do you have time to have a meeting with me?

**Comment by FilipinaW** [comment]
sure

**Comment by zxdong262** [comment]
@FilipinaW Please send an email to drake.zhao@ringcentral.com, I will reply you the meeting link.

**Comment by zxdong262** [comment]
Close it now, feel free to submit another if needed, feedbacks are always welcome.
