### ISSUE TITLE
Extension hiding under Pipedrive's black ribbon on top of the screen

### ISSUE THREAD

**Issue by FilipinaW** [ringcentral/pipedrive-embeddable-ringcentral-phone-spa#23]
When you move the extension over/on top of the black bar that's part of Pipedrive - the part of extension under it becomes invisible.  You lose access to all the menus and top extension bar that would let you move it back to a different place.  Even when I reinstalled it - it came back in the same place - I had to play around with chrome to gain access back to extension....

**Comment by zxdong262** [comment]
v0.8.6 should fix now, thank you for the feedback! @FilipinaW
