### ISSUE TITLE
Call not logging 07 to +44

### ISSUE THREAD

**Issue by JPavey** [ringcentral/pipedrive-embeddable-ringcentral-phone-spa#25]
When making a call directly from Pipedrive without the country code, its not logging, is there a workaround?

e.g. Person in Pipedrive has phone number 0123456789

Though when making the call through RingCentral its ringing through as +44123456789 so the call isn't being logged into the person onto Pipedrive after the call.

How would I go about fixing this?

**Comment by zxdong262** [comment]
Can you try click reload contacts in contacts panel? And make sure you are using the lastest release.

<img width="317" alt="Screen Shot 2019-10-23 at 9 49 56 AM" src="https://user-images.githubusercontent.com/1641949/69180370-27b5d400-0b48-11ea-85fd-0c0b3a8b104c.png">

**Comment by zxdong262** [comment]
Close it now, feel free to submit another if needed, feedbacks are always welcome.
