### ISSUE TITLE
Syncing contacts and deals error

### ISSUE THREAD

**Issue by franklam2008** [ringcentral/pipedrive-embeddable-ringcentral-phone-spa#26]
it keeps trying to authorize in the ring central widget, and syncing deals and contacts back and forth.
![Screenshot (1)](https://user-images.githubusercontent.com/41360206/69188499-a67c2400-0aea-11ea-9f40-cd406d2ec4c2.png)

**Comment by franklam2008** [comment]
and showing no contacts and no data connected to this person.

**Comment by zxdong262** [comment]
Just released new version, can you try it?  https://github.com/ringcentral/pipedrive-embeddable-ringcentral-phone-spa/releases/tag/v1.2.3

**Comment by franklam2008** [comment]
For sure. thank you Xudong.

**Comment by franklam2008** [comment]
Yeah, the syncing bug is fixed. great job, appreciate it!

**Comment by franklam2008** [comment]
Use another phone number to test it, it doesn't ask for a new contact, so I created one with the new number, but it doesn't sync with the ring central contact. I tried the 1.2.4 version but no luck.

![Screenshot (4)](https://user-images.githubusercontent.com/41360206/69192291-48ebd580-0af2-11ea-8ce0-07ec6e98806b.png)

**Comment by zxdong262** [comment]
@franklam2008 When you add new contacts, need click reload contacts button to sync new contacts.
<img width="317" alt="Screen Shot 2019-10-23 at 9 49 56 AM" src="https://user-images.githubusercontent.com/1641949/69193839-ab7cba00-0b62-11ea-8edf-03a2977e5a19.png">

**Comment by franklam2008** [comment]
Got it thank you! just a question that you probably thought of, why can't we put a script for an interval to update the contact every minute? you know sales reps are all not good at computer, they wont remember to refresh it everytime.

**Comment by zxdong262** [comment]
@franklam2008 Good idea! Maybe one hour, some user may have tens of thousands of contacts, I will think about this.

**Comment by franklam2008** [comment]
thank you, maybe just put an IIFE trigger contact refresh when the webpage refresh or starts.

**Comment by zxdong262** [comment]
Close it now, feel free to submit another if needed, feedbacks are always welcome.
