### ISSUE TITLE
RC to Pipedrive - call log sync not working

### ISSUE THREAD

**Issue by cloudcomputercompany** [ringcentral/pipedrive-embeddable-ringcentral-phone-spa#27]
Newbie to this extension, so bear with me.
Have installed the xtension as per instructions, works as expected with users being able to make calls straight from pipe drive, but there is no record of the call going back to pipedrive.

Any thoughts?

Thanks.

**Comment by zxdong262** [comment]
Please check this post about auto log feature: https://github.com/ringcentral/hubspot-embeddable-ringcentral-phone/issues/137 to see if you can get it done. Let me know if you still have problems. Feedbacks are always welcome, feel free to ask.

**Comment by cloudcomputercompany** [comment]
Hi,

Thanks for the reply. Not seeing the Autolog calls in the RC settings.

Mathew



<https://www.cloudcomputercompany.com.au/>
Mathew Hoffman  |  CEO & Cloud Specialist
1800 312 972
mathew@cloudcomputercompany.com.au
[image: Facebook] <https://www.facebook.com/cloudcomputerco>
[image: LinkedIn] <https://www.linkedin.com/thehoff>
[image: Twitter] <https://www.twitter.com/hofftek>

**Comment by zxdong262** [comment]
@cloudcomputercompany Can you give some screenshot about it? Or do you have time to have a meeting with me, you can send a email to drake.zhao@ringcentral.com, with your timezone and avaiable time range, I will shedule the meeting and send you the meeting link.

**Comment by cloudcomputercompany** [comment]
Hi,

Managed to get it up and running on one device. I have a few more to go. Is
there anything that can block the extension?

Mathew



<https://www.cloudcomputercompany.com.au/>
Mathew Hoffman  |  CEO & Cloud Specialist
1800 312 972
mathew@cloudcomputercompany.com.au
[image: Facebook] <https://www.facebook.com/cloudcomputerco>
[image: LinkedIn] <https://www.linkedin.com/thehoff>
[image: Twitter] <https://www.twitter.com/hofftek>

**Comment by zxdong262** [comment]
@cloudcomputercompany Make sure you **turn off** `Block third-party cookies` in `chrome://settings/content/cookies`, by default it is **off**

**Comment by cloudcomputercompany** [comment]
Thanks that worked, however calls not being logged.



<https://www.cloudcomputercompany.com.au/>
Mathew Hoffman  |  CEO & Cloud Specialist
1800 312 972
mathew@cloudcomputercompany.com.au
[image: Facebook] <https://www.facebook.com/cloudcomputerco>
[image: LinkedIn] <https://www.linkedin.com/thehoff>
[image: Twitter] <https://www.twitter.com/hofftek>

**Comment by zxdong262** [comment]
@cloudcomputercompany Do you have time to have a meeting with me, you can send a email to drake.zhao@ringcentral.com, with your timezone and avaiable time range, I will shedule the meeting and send you the meeting link.

**Comment by cloudcomputercompany** [comment]
I'm have had to escalate this... Matt Wilson is my partner manager for
ringcentral here in Australia. Matt will be reaching out  to you.

BTW is there a mobile version of your app?

Mathew

**Comment by zxdong262** [comment]
No, there is no mobile version for this extension, I have created another video to show how it works, it may helps: https://youtu.be/lhjPLU95B6Q

**Comment by cloudcomputercompany** [comment]
Thanks.. I will give it a go.

Mathew



<https://www.cloudcomputercompany.com.au/>
Mathew Hoffman  |  CEO & Cloud Specialist
1800 312 972
mathew@cloudcomputercompany.com.au
[image: Facebook] <https://www.facebook.com/cloudcomputerco>
[image: LinkedIn] <https://www.linkedin.com/thehoff>
[image: Twitter] <https://www.twitter.com/hofftek>

**Comment by cloudcomputercompany** [comment]
Hi,

Have been doing some more testing and it appears that when a call is made
from the extension, it is adding the call data to the wrong pipe drive
contact.

Attached are screen shots.

Mathew



<https://www.cloudcomputercompany.com.au/>
Mathew Hoffman  |  CEO & Cloud Specialist
1800 312 972
mathew@cloudcomputercompany.com.au
[image: Facebook] <https://www.facebook.com/cloudcomputerco>
[image: LinkedIn] <https://www.linkedin.com/thehoff>
[image: Twitter] <https://www.twitter.com/hofftek>

**Comment by zxdong262** [comment]
@cloudcomputercompany Images from email will not show in github issue.

**Comment by cloudcomputercompany** [comment]
Ok so how can I send the pic to you so you can view?



<https://www.cloudcomputercompany.com.au/>
Mathew Hoffman  |  CEO & Cloud Specialist
1800 312 972
mathew@cloudcomputercompany.com.au
[image: Facebook] <https://www.facebook.com/cloudcomputerco>
[image: LinkedIn] <https://www.linkedin.com/thehoff>
[image: Twitter] <https://www.twitter.com/hofftek>

**Comment by zxdong262** [comment]
@cloudcomputercompany youcan directly send email to my email address zxdong@gmail.com or upload image in github issue.

**Comment by zxdong262** [comment]
Close it now, feel free to submit another one if needed.

**Comment by cloudcomputercompany** [comment]
Thanks for your help



<https://www.cloudcomputercompany.com.au/>
Mathew Hoffman  |  CEO & Cloud Specialist
1800 312 972
mathew@cloudcomputercompany.com.au
[image: Facebook] <https://www.facebook.com/cloudcomputerco>
[image: LinkedIn] <https://www.linkedin.com/thehoff>
[image: Twitter] <https://www.twitter.com/hofftek>
