### ISSUE TITLE
Pipe Drive web application messed up with the last 2 versions

### ISSUE THREAD

**Issue by jguliker** [ringcentral/pipedrive-embeddable-ringcentral-phone-spa#36]
With the last 2 updates the Pipedrive contacts list: contacts overlap, The activities page some lines are missing etc...
It all works good when I turn off the Ring Central chrome extension. 

![capture 2](https://user-images.githubusercontent.com/58612802/79919630-9d69e880-83e3-11ea-9502-d399494a1e0d.jpg)

**Comment by zxdong262** [comment]
Released 2.0.3 to fix it, thank you for the feedback!
