### ISSUE TITLE
Notes section 

### ISSUE THREAD

**Issue by Sil73** [ringcentral/pipedrive-embeddable-ringcentral-phone-spa#37]
When calling via RingCentral to a Pipedrive contact, the note section does not automatically save to the contacts file when the call is finished. I have to go to history and enter it that way for it to save.

![image](https://user-images.githubusercontent.com/64503473/80542726-e841bc80-89f0-11ea-83ee-e5ea19480534.png)

![image](https://user-images.githubusercontent.com/64503473/80542792-06a7b800-89f1-11ea-84ad-7bc3b546b253.png)

**Comment by zxdong262** [comment]
@Sil73 Have you turn the auto log on in setting? And it take a few seconds to wait for the sync event to come. If you already turn it on and waited but still no auto sync, that is somgthing I can not reproduce, then can we have a meeting to check it? If you can, please send a email to zxdong@gmail.com with your available time and timezone, do not post here, meeting link can only be sent with email for security reason.

**Comment by Sil73** [comment]
> @Sil73 Have you turn the auto log on in setting? And it take a few seconds to wait for the sync event to come. If you already turn it on and waited but still no auto sync, that is somgthing I can not reproduce, then can we have a meeting to check it? If you can, please send a email to [zxdong@gmail.com](mailto:zxdong@gmail.com) with your available time and timezone, do not post here, meeting link can only be sent with email for security reason.

**Comment by Sil73** [comment]
@zxdong262 I have the auto log calls and auto log messages on. Will send you an email to discuss further.
