### ISSUE TITLE
PipeDrive Logging Issue

### ISSUE THREAD

**Issue by jin-fhg** [ringcentral/pipedrive-embeddable-ringcentral-phone-spa#38]
Hello @zxdong262 

I would like to raise a strange issue from one of our RingCentral customers. The issue is that when they initiate an outbound call, the log does not save to the contact person's activity history, but it is being saved in their company contact record. I have a video of this issue attached to this case as well as the console and HAR files. 

[allinoneconsulting-096b17.pipedrive.com-1588104931318.log](https://github.com/ringcentral/pipedrive-embeddable-ringcentral-phone-spa/files/4548839/allinoneconsulting-096b17.pipedrive.com-1588104931318.log)

https://drive.google.com/file/d/1DOEAwv5Dl3JNVUYyX60aKzatPZb9Exdj/view?usp=sharing

Video: 
https://drive.google.com/file/d/1pSv3pUyZby1wk-1aS3qO6dB6QUX_8Z_b/view?usp=sharing

**Comment by zxdong262** [comment]
Can we have a meeting to check it?

**Comment by zxdong262** [comment]
The only possible situation I can think of is the all in one contact previously had the number, then removed, but the data not syned.

**Comment by jin-fhg** [comment]
I see. May I know your availability for the meeting and I will coordinate with the user?

**Comment by jin-fhg** [comment]
According to the customer, the best time is either 10 AM or 1 PM EST. Which one do you prefer?

**Comment by jin-fhg** [comment]
I have scheduled it a 1 PM EST. Please check you email for the meeting invite

**Comment by zxdong262** [comment]
@jin-fhg OK, see you then

**Comment by jin-fhg** [comment]
Thank you @zxdong262
