### ISSUE TITLE
Auto syncing not working

### ISSUE THREAD

**Issue by jkushner** [ringcentral/pipedrive-embeddable-ringcentral-phone-spa#39]
Installed this extension and see it in the lower right of my window when inside pipedrive, but the following features don't seem to work:
1. Auto sync call logs/recordings to contacts - after recording a call and hanging up, no record of it appears in the contact's timeline. I waited about 10 minutes and kept refreshing, nothing is posted.

2. Auto sync of SMS to contacts - after sending an sms to a contact from the widget itself, still no record of it appears on the contact's timeline. Again, tried refreshing, but it flat out doesn't work.

Can others reproduce these issues? Does the window need to be open with plugin running for these auto sync features to work? Plugin v 2.5.1 in chrome 81.0 on macos 10.15

**Comment by zxdong262** [comment]
Have you turn the auto log on in setting page?
