### ISSUE TITLE
Ring Central chrome extension for pipedrive not functioning correctly

### ISSUE THREAD

**Issue by LordMegatron91372** [ringcentral/pipedrive-embeddable-ringcentral-phone-spa#4]
1. When a call comes in to ringcentral widget for pipedrive, it redirects the page to the deal page, even if you are editing a file.

2. When a call comes into ringcentral widget for pipedrive, the contact page only displays half way, cant see the name.

**Comment by zxdong262** [comment]
Hi @LordMegatron91372 

Thank you for the feedback, Released new version to fix the UI , related to problem 2, for problem 1, I can not reproduce, can you provide more detail about how to reproduce this, and any case this do not happen?

**Comment by LordMegatron91372** [comment]
Thank you for the fix, but a few more bugs.

1) When deal opens up on the browser when a call comes in , the deal is not opening fully so we can see the entire deal, left and right margins are not set wide enough.

2) When there is over 10 minutes of inactivity the widget will time out and give a red warning box on top of widget that reads Session Expired.

3) Is there a way to stop the browser from opening up a new tab on the browser when a call comes in ?

**Comment by zxdong262** [comment]
Hi @LordMegatron91372 about 3, I can not reproduce this in my Chrome, can you reproduce it in Incognito window?

**Comment by LordMegatron91372** [comment]
can you produce #4?

**Comment by LordMegatron91372** [comment]
ALSO in the ring central widget, there are some names (Contacts) that dont come up from pipedrive, is there a fix for this

**Comment by zxdong262** [comment]
@LordMegatron91372 Did you applied the pipedrive filter?

**Comment by LordMegatron91372** [comment]
It only gives me the option of authorization of Pipedrive

**Comment by zxdong262** [comment]
<img width="307" alt="Screen Shot 2019-04-04 at 8 43 46 AM" src="https://user-images.githubusercontent.com/1641949/55522020-cd99f880-56b5-11e9-9c61-fd5a17904aad.png">

**Comment by LordMegatron91372** [comment]
Yes the filter is on all

**Comment by zxdong262** [comment]
@LordMegatron91372 Only when set the filter to pipedrive, it will show only pipedrive contacts.

**Comment by LordMegatron91372** [comment]
Tried that, but some contacts still not showing

**Comment by zxdong262** [comment]
@LordMegatron91372 How many contacts do you have?

**Comment by LordMegatron91372** [comment]
Around 120

**Comment by zxdong262** [comment]
@LordMegatron91372 Released new version, can you try it, and let know how it works, thank you.

https://github.com/ringcentral/pipedrive-embeddable-ringcentral-phone-spa/releases/tag/v0.4.2

**Comment by LordMegatron91372** [comment]
![Screenshot (8)](https://user-images.githubusercontent.com/48811144/55742081-d57ed300-59fc-11e9-82e0-bb65829a529b.png)

**Comment by zxdong262** [comment]
Add scrolls to the popup

https://github.com/ringcentral/pipedrive-embeddable-ringcentral-phone-spa/releases/tag/v0.4.3

**Comment by zxdong262** [comment]
Hi @LordMegatron91372 how is the call log sync working?

**Comment by LordMegatron91372** [comment]
![Screenshot (9)](https://user-images.githubusercontent.com/48811144/55771693-0be93c00-5a57-11e9-8f5a-20a0f175f04c.png)
This is the error i get when trying to load extension for 4.3 version

**Comment by LordMegatron91372** [comment]
I fixed the last issue, thank you for making it scrollable but the width of the popup is still not wide enough for my agents to see all deal info, please make popup fill the size of the monitor (Screen)

**Comment by zxdong262** [comment]
https://github.com/ringcentral/pipedrive-embeddable-ringcentral-phone-spa/releases/tag/v0.4.4 Now fullscreen width.

**Comment by LordMegatron91372** [comment]
4.4  fixed all the above issues, thank you for the prompt response and fixes.

i have requests

1. Click to Call in Pipedrive does not work, when i click on a number to make a call it will let me choose the phone # but when i tap on the phone # it will not initiate the call on my RING CENTRAL DESKTOP APP. It starts on the widget and then  it disappears.

2. Can you make the popup ring central widget stay in the down position when a call is coming in, because my desktop app is already open and it is taking up to much space on my screen when i am trying to view customer information.

thank You

**Comment by zxdong262** [comment]
Close it now, feel free to submit another if needed, feedbacks are always welcome.
