### ISSUE TITLE
SMS and Calls - going to random accounts

### ISSUE THREAD

**Issue by kwarrington** [ringcentral/pipedrive-embeddable-ringcentral-phone-spa#42]
This is only happening with one phone number.  It is going into Dino's account which is correct, but also in Null and then all of these other random accounts.  
![2020-07-24_13-29-02](https://user-images.githubusercontent.com/64229487/88424073-8952d000-cdb2-11ea-8472-25cea61aea16.png)

**Comment by zxdong262** [comment]
Are you using latest release?

**Comment by kwarrington** [comment]
We have more than one user.  I know the one that reported the issue is on the latest release, but a user that doesn't use Pipedrive that often might be on the previous release.

Sent from my iPhone

On Jul 25, 2020, at 9:16 AM, ZHAO Xudong <notifications@github.com> wrote:

?

Are you using latest release?

-

**Comment by zxdong262** [comment]
@kwarrington I can not reproduce this issue in latest release, old release do have this bug, can you confirm it is caused by the user using latest release or other user using old release?

If confirmed it is leatest release, can we have a meeting to check it? If you can, pelase send me available time/timezone to drake.zhao@ringcentral.com

**Comment by kwarrington** [comment]
Ok.  Thanks.  We will make sure to upgrade other user.

Sent from my iPhone

On Jul 25, 2020, at 2:01 PM, ZHAO Xudong <notifications@github.com> wrote:

?

@kwarrington<https://github.com/kwarrington> I can not reproduce this issue in latest release, old release do have this bug, can you confirm it is caused by the user using latest release or other user using old release?

If confirmed it is leatest release, can we have a meeting to check it? If you can, pelase send me available time/timezone to drake.zhao@ringcentral.com<mailto:drake.zhao@ringcentral.com>

-
