### ISSUE TITLE
Having issues with my build - Uncaught TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by roozbehk** [ringcentral/pipedrive-embeddable-ringcentral-phone-spa#45]
Hi All, 

I am running  command ```npm i``` ```npm run pack``` , upload the dist folder to chrome and I am getting this error which is causing the extension not to work. i only changed the following in config.js

    clientID: '****',
    clientSecret: '***',

and
   serviceName: 'PipeDriveCRM'

I am using Node version v12.18.3

**Comment by zxdong262** [comment]
Sorry @roozbehk , I missed one prop in config.default, you can pull latest code, it will be fine.
