### ISSUE TITLE
How I get the embed to work with platform.devtest.ringcentral.com

### ISSUE THREAD

**Issue by roozbehk** [ringcentral/pipedrive-embeddable-ringcentral-phone-spa#46]
Hi I like to use my own clientID and SecretID, but in order to submit my app for production, i need to make some calls through the sandbox. I have changed the appServer to :  platform.devtest.ringcentral.com and compiled the extension. when I sign in I can not get the Oauth to return and redirect, I am getting following error when tyr to sign in. 

```
{
  "error" : "invalid_grant",
  "errors" : [ {
    "errorCode" : "OAU-109",
    "message" : "Redirect URIs do not match"
  } ],
  "error_description" : "Redirect URIs do not match"
}
```

I have included the https://ringcentral.github.io/ringcentral-embeddable/redirect.html for my oAuth redirect and the app in sandbox is for web, javascript. 

Please tell me what I am doing wrong.

**Comment by roozbehk** [comment]
Hello, is there a forum that i can get assistance with this?

**Comment by zxdong262** [comment]
Check this https://github.com/ringcentral/hubspot-embeddable-ringcentral-phone/issues/209#issuecomment-665351544

Also, you can directly use all api from https://developers.ringcentral.com/api-reference to fufill the production requirement

<img width="1440" alt="Screen Shot 2020-08-20 at 7 59 17 PM" src="https://user-images.githubusercontent.com/1641949/90767366-adf18780-e31f-11ea-8b4b-65139267a456.png">

And forum: https://developers.ringcentral.com/go-to-community.html
