### ISSUE TITLE
Pipedrive SMS Log marked as DONE even if it's still unread in RingCentral

### ISSUE THREAD

**Issue by TNDevSupport** [ringcentral/pipedrive-embeddable-ringcentral-phone-spa#48]
Call and SMS logs work well after the last update. Pipedrive Deal Cards has a notification system if there's any missed call or unread SMS. Right now, all SMS are instantly logged as DONE with a green check even if it's still unread. Can we make that work that way?

**Comment by zxdong262** [comment]
https://github.com/ringcentral/pipedrive-embeddable-ringcentral-phone-spa/releases
In latest release, fixed it.

Thank you for the feeedback

**Comment by TNDevSupport** [comment]
Wow, I just want to thank you for the quick revert. You guys are amazing!
