### ISSUE TITLE
Include Missed Calls and Unread Voice Mail as "Not Done" Status in Pipedrive Call Logs

### ISSUE THREAD

**Issue by TNDevSupport** [ringcentral/pipedrive-embeddable-ringcentral-phone-spa#49]
Please include Missed Calls and Unread Voice Mail as "Not Done" Status in Pipedrive Call Logs.

You guys are amazing, less than 24-hour turnaround for creating updates!

**Comment by zxdong262** [comment]
Finally done: https://github.com/ringcentral/pipedrive-embeddable-ringcentral-phone-spa/releases/tag/v2.11.0
Thank you for the feedback! @TNDevSupport
