### ISSUE TITLE
SMS messages are going to a random customer deal on each message

### ISSUE THREAD

**Issue by kwarrington** [ringcentral/pipedrive-embeddable-ringcentral-phone-spa#53]
sms messages are going to the correct contact and the correct customer, but it is also going to a random customer deal every time.

![image](https://user-images.githubusercontent.com/64229487/94592262-8363ea00-024e-11eb-8fc5-0f3b551f491f.png)

**Comment by zxdong262** [comment]
Removed log to deal function:
https://github.com/ringcentral/pipedrive-embeddable-ringcentral-phone-spa/releases/tag/v2.11.2
