### ISSUE TITLE
Stuck at Syncing & Wont Update Calls.

### ISSUE THREAD

**Issue by incognitozen** [ringcentral/pipedrive-embeddable-ringcentral-phone-spa#6]
I got

Latest Chrome Extension 0.44
Ringcentral Log in to the widget works fine.

When making calls , it doesnt recognise the contact. Further the Pipe drive button stuck at syncing. I do have a very large number of contacts. Close to 20K.

On Console

app.js:1 Time out
(anonymous) @ app.js:1

**Comment by incognitozen** [comment]
Also won' sync calls into the Pipedrive system.

**Comment by zxdong262** [comment]
@incognitozen Before it finish syncing, nothing will work. 20k, it may take some time to sync all contacts, can you wait it to finish syncing? and watch the console, to see if there is any errors, post the logs here if possible.

**Comment by derrickb1982** [comment]
I am having the same issues

**Comment by derrickb1982** [comment]
it is definitely the amount of contacts, I have tried on other users with less and it works fine. Is there a way to have it auto log to Deal as well? it seems to only log to people and organization

**Comment by incognitozen** [comment]
Hey @zxdong262 

Thanks for the quick response. I have been waiting over a day and it still is stuck at syncing.
Is there perhaps a method that I can use to expediate the syncing ?
Or perhaps we can introduce a mechanism to allow for small batch syncing ? Perhaps a 100 record sync first before it keeps going ?

**Comment by zxdong262** [comment]
@incognitozen Thank you for the feedback, I will find a solution about this.

**Comment by zxdong262** [comment]
@incognitozen Released new version. Now it will load contacts in background, feed first 100 contacts first, before the full load, the contacts not loading will not be available. In left bottom corner there will be a sync text: loading contacts.

https://github.com/ringcentral/pipedrive-embeddable-ringcentral-phone-spa/releases/tag/v0.4.6

**Comment by incognitozen** [comment]
Yes this is working and is working well. I think this issue can be closed.
