### ISSUE TITLE
Is there a way to have it auto log to Deal as well? it seems to only log to people and organization

### ISSUE THREAD

**Issue by zxdong262** [ringcentral/pipedrive-embeddable-ringcentral-phone-spa#7]
Is there a way to have it auto log to Deal as well? it seems to only log to people and organization

_Originally posted by @derrickb1982 in https://github.com/ringcentral/pipedrive-embeddable-ringcentral-phone-spa/issues/6#issuecomment-481832455_

**Comment by incognitozen** [comment]
This was going to be my next questions. At this moment it only sycns to contacts and not to the deals. I am afraid this makes it hard to view everything under one deal.

**Comment by derrickb1982** [comment]
I noticed the time stamp seems to be off, it always puts the time called as sometime early in the morning not the actual time of the call. also is there a way to auto sync/ attach the call recording as well?

**Comment by derrickb1982** [comment]
any updates on logging the call to deal?

**Comment by zxdong262** [comment]
@derrickb1982 Sorry for the delay, seems need more work to make it work, maybe two weeks.

**Comment by derrickb1982** [comment]
any update?

**Comment by zxdong262** [comment]
@derrickb1982 Sorry for the delay, maybe next week.

**Comment by zxdong262** [comment]
https://github.com/ringcentral/pipedrive-embeddable-ringcentral-phone-spa/releases/tag/v0.5.0

@derrickb1982 Released with syncing to deal feature.

**Comment by derrickb1982** [comment]
@zxdong262 I tried the new release and still only logs to Org and Person not the Deal, the time stamp for recording the call seems to be off 7 hours, example if I call at 10 am it will show that I called at 3 am instead thanks for your help

**Comment by zxdong262** [comment]
@derrickb1982 Are you in same timezone when you make the call and do the sync? Pipedrive do not provide timezone option when log call event, so if you do these two action in different timezone, it could cause this.

**Comment by zxdong262** [comment]
@derrickb1982 Can you provide a HAR file when syncing? In my test account it do works. maybe there is some problem I do not know. You can send to drake@ringcentral.com if you can.

**Comment by ivydrake** [comment]
Hi, I work with @derrickb1982, the new 0.5.4 update fixed the time stamp issue! Thank you so much!! We still can not get the call log it to auto log to the deal. It only posts to the person and org. Any updates that could fix this?

**Comment by zxdong262** [comment]
@ivydrake Sorry missed the message, in my test env, it still works fine, I guess there is some situation I never know, if you can have a meeting with me, I can try to find out why it happens.

Anyway, if you can have a meeting with me next week or later, you can send your available time and your timezone to my email: drake.zhao@ringcentral.com, I will set the meeting link, any time works for me.

**Comment by zxdong262** [comment]
Close it now, feel free to submit another if needed, feedbacks are always welcome.
