### ISSUE TITLE
Errors - hovering over phone number not doing anything

### ISSUE THREAD

**Issue by caseyrankin** [ringcentral/pipedrive-embeddable-ringcentral-phone-spa#84]
Getting errors with latest version and it is not showing the call option with ring central when hovering over a phone number

![image](https://user-images.githubusercontent.com/1229043/147280335-b7b33a4e-476b-498d-98ba-950b4c3eab2b.png)

**Comment by zxdong262** [comment]
Confirm resolved by v3.5.1
