### ISSUE TITLE
Time Stamp of Call Off 

### ISSUE THREAD

**Issue by derrickb1982** [ringcentral/pipedrive-embeddable-ringcentral-phone-spa#9]
is it possible to have the call activity log to Deals?

**Comment by derrickb1982** [comment]
time stamp is off when it logs the call

**Comment by zxdong262** [comment]
> time stamp is off when it logs the call

Can you explain this in detail? I do not understand it.

**Comment by derrickb1982** [comment]
it’s not accurately recording the proper time the call was made, usually off by hours

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by derrickb1982** [comment]
any updates on fixing the call time issue?

**Comment by zxdong262** [comment]
@derrickb1982 Sorry for the delay, I checked again seems nothing wrong, I guess it is because the timezone problem, since the activity creation only support `hh:mm` for time, so it will use the timezone when you do sync operation, not the timezone the made the call, can you confirm about this?

**Comment by incognitozen** [comment]
Unfortunately no.

It seems that the time log for me is delayed by 2 hours.

So for an example, I am in AEST time Zone Melbourne.
I called at 5:01 PM.
The system did not immediately log the call but in the next 5 mins logged it at 3:01PM

**Comment by zxdong262** [comment]
@incognitozen Thank you for the feedback, I will check this again.

**Comment by zxdong262** [comment]
https://github.com/ringcentral/pipedrive-embeddable-ringcentral-phone-spa/releases/tag/v0.4.12

I think I fix this now, can you try it?

**Comment by zxdong262** [comment]
https://github.com/ringcentral/pipedrive-embeddable-ringcentral-phone-spa/releases/tag/v0.5.4 Please try the latest release, should fix now, thank you for the feedback.
