### ISSUE TITLE
Sync call log message from a deal to "participants" and not to the "person".

### ISSUE THREAD

**Issue by CoCraig** [ringcentral/pipedrive-embeddable-ringcentral-phone-spa#98]
> Hello, when I want to sync up a call log or message with a person from a deal on the RingCentral Pipedrive app it only lets me do that from the drop down if they are under "Person" in the deal. Is it possible to do that with the "Participants" also?

Pipedrive defines [participants](https://support.pipedrive.com/en/article/participants)

**Comment by zxdong262** [comment]
Checked docs and UI, and tested, confirmed can not do this, since filter condition support person, do not support participant
